"""Generate a synthetic earthquake catalog for the research-loop demo.

The catalog is one region's ~10 years of recorded earthquakes. Above the
magnitude of completeness MC, magnitudes follow the Gutenberg-Richter law

    log10 N(>=M) = a - b * M

so (M - MC) is exponentially distributed. The signal is deliberately simple and
fully documented so its parameters can be treated as GROUND TRUTH when validating
a b-value analysis.

Magnitudes are drawn with the exponential floor at ``MC - DELTA_M/2`` and then
rounded to ``DELTA_M`` (0.1), so every reported bin (2.0, 2.1, ...) is a full,
centered bin. The Aki-Utsu maximum-likelihood estimator

    b_hat = log10(e) / (mean(M) - (MC - DELTA_M/2))

is then effectively unbiased (a negligible 0.1-magnitude binning residual aside) and recovers B_VALUE to well within sampling error.

Generation is deterministic (fixed SEED), so the committed
``earthquake_catalog.csv`` can be regenerated byte-for-byte.

Run with: pixi run python samples/seismic/generate_catalog.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

# --- Ground-truth parameters (also documented in GROUND_TRUTH.md) ---
B_VALUE = 0.8        # Gutenberg-Richter b-value — the answer the research loop recovers
MC = 2.0             # magnitude of completeness (catalog is complete at/above this)
DELTA_M = 0.1        # magnitude reporting bin width
N_EVENTS = 3000      # number of recorded events above MC
SEED = 20260618      # RNG seed (this is also the data's provenance)
START = "2014-01-01"
END = "2024-01-01"


def generate() -> pd.DataFrame:
    """Return the synthetic catalog as a DataFrame with time, magnitude columns."""
    rng = np.random.default_rng(SEED)
    # Magnitudes: exponential above (MC - DELTA_M/2), reported on the 0.1 grid.
    u = rng.random(N_EVENTS)
    mags = (MC - DELTA_M / 2) - np.log10(u) / B_VALUE
    mags = np.round(mags, 1)
    # Origin times: uniform over the window, sorted ascending.
    start = pd.Timestamp(START)
    span_seconds = (pd.Timestamp(END) - start).total_seconds()
    offsets = np.sort(rng.uniform(0.0, span_seconds, size=N_EVENTS))
    times = start + pd.to_timedelta(offsets, unit="s")
    return pd.DataFrame(
        {"time": times.strftime("%Y-%m-%dT%H:%M:%S"), "magnitude": mags}
    )


def main() -> None:
    out = Path(__file__).with_name("earthquake_catalog.csv")
    df = generate()
    df.to_csv(out, index=False)
    print(f"Wrote {len(df)} rows to {out}")


if __name__ == "__main__":
    main()
