"""Generate a synthetic buoy sea-surface-temperature (SST) series.

The signal is deliberately simple and fully documented so its parameters can be
treated as GROUND TRUTH when validating a trend analysis:

    sst(t) = MEAN + AMP * sin(2*pi*doy/365.25 + PHASE) + WARMING * years + noise

Generation is deterministic (fixed SEED), so the committed ``buoy_sst.csv`` can
be regenerated byte-for-byte.

Run with: pixi run python samples/ocean/generate_buoy_sst.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

# --- Ground-truth parameters (also documented in README.md) ---
MEAN = 14.0          # °C, annual-mean SST
AMP = 5.0            # °C, seasonal amplitude
PHASE = -1.5         # radians, shifts the seasonal peak toward late summer
WARMING = 0.03       # °C per year — the trend the research loop should recover
NOISE_SD = 0.5       # °C, daily observational noise
SEED = 20260608      # RNG seed (this is also the data's provenance)
START = "2014-01-01"
N_DAYS = 365 * 10 + 3  # 3653 daily samples: 2014-01-01 through 2024-01-01 inclusive


def generate() -> pd.DataFrame:
    """Return the synthetic SST series as a DataFrame with date, sst_c columns."""
    rng = np.random.default_rng(SEED)
    dates = pd.date_range(START, periods=N_DAYS, freq="D")
    doy = dates.dayofyear.to_numpy()
    years = (dates - dates[0]).days.to_numpy() / 365.25
    seasonal = AMP * np.sin(2 * np.pi * doy / 365.25 + PHASE)
    trend = WARMING * years
    noise = rng.normal(0.0, NOISE_SD, size=N_DAYS)
    sst = MEAN + seasonal + trend + noise
    return pd.DataFrame(
        {"date": dates.strftime("%Y-%m-%d"), "sst_c": np.round(sst, 3)}
    )


def main() -> None:
    out = Path(__file__).with_name("buoy_sst.csv")
    df = generate()
    df.to_csv(out, index=False)
    print(f"Wrote {len(df)} rows to {out}")


if __name__ == "__main__":
    main()
